export const researchProjects = [
  {
    slug: "planning-execution-failures",
    title: "LLM Agent 的规划与执行失效诊断",
    period: "2026.09 — 持续探索",
    question: "当一个 Agent 没有完成任务，问题究竟出在规划、证据获取，还是执行过程？",
    finding: "显式规划改变了交付与停止行为，却未稳定解决最终正确性；本实现中的事后验证增加成本，没有带来最终通过率的净提升。",
    methods: "对照实验 / 工具使用 / 失败诊断",
    repo: "https://github.com/ZhansLeo/planning-execution-failures",
    intro: "以长程、多约束旅行规划作为实验环境，考察工具增强 Agent 的证据获取、执行控制、实体落地和全局约束满足。旅行是测试场景，关注的是系统在哪一步失效。",
    design: "TravelPlanner 在相同的 180 个验证问题上比较四种设置：给定官方参考信息直接规划（TP-A）、自主检索的 ReAct（TP-B）、加入显式 Planner（TP-C）、独立的 TP-C 链加事后 Verifier 与至多一次 Replan（TP-D）。ChinaTravel 以 12 个配对问题做小规模机制检查。",
    columns: ["设置", "交付率", "最终通过率", "Tokens / 问题"],
    rows: [["TP-A · 给定证据", "95.0%", "13.89%", "10.9k"], ["TP-B · ReAct", "35.0%", "15.56%", "57.6k"], ["TP-C · Planner", "40.0%", "16.11%", "56.0k"], ["TP-D · Verifier", "41.67%", "16.11%", "63.0k"]],
    observations: ["从给定证据走向自主获取证据，暴露出停止控制和无法交付等系统问题。", "结构合法的规划蓝图，不保证后续执行忠实于计划或有充分证据。", "ChinaTravel 中，一些表面上的效率增益来自过早停止，需要结合执行轨迹解释。"],
    limitations: "TP-A 与 TP-B 同时改变了证据获取、系统责任和交互方式，不是只改变工具的因果消融。ChinaTravel 只有 12 个配对样本，不用于基准排名。结论仅适用于记录的模型、协议与实现，不能推广为规划器或验证器普遍无效。",
    contribution: "个人完成实验代码、工具适配、评测编排、分层指标与错误分类，并整理冻结结果、代表案例和可复现说明。",
    next: "继续区分证据不足、停止控制和约束落实问题，检验更早介入的验证机制是否有效。后续实验使用明确的新协议，与当前冻结结果分开记录。",
  },
  {
    slug: "small-llm-math-reasoning-lab",
    title: "小参数语言模型的数学推理实验",
    period: "2026.08 — 2026.09",
    question: "更规范的回答格式，是否意味着模型真的更会推理？",
    finding: "LoRA 微调将严格格式遵循率提高到 99% 以上，但数学正确率下降；错误导向选样相对随机选样未呈现显著优势。",
    methods: "冻结评测 / LoRA / 配对统计 / 错误分析",
    repo: "https://github.com/ZhansLeo/small-llm-math-reasoning-lab",
    intro: "围绕 Qwen2.5-0.5B-Instruct 与 GSM8K，建立从基线评测、错误诊断到提示干预、微调及冻结测试集复评的实验闭环。重点是理解干预改变了什么，而不是追求一次高分。",
    design: "使用预先冻结的 GSM8K test IDs 101–300，共 200 题；固定 greedy decoding 与 evaluator v4。比较基础模型、随机选样 LoRA-SFT 和错误导向 LoRA-SFT，分别使用 Prompt A 与结构化 Prompt C。",
    columns: ["模型设置", "Prompt A 正确率", "Prompt C 正确率", "严格格式 A / C"],
    rows: [["基础模型", "47.0%", "41.0%", "0% / 0%"], ["随机 SFT", "34.5%", "30.0%", "99% / 99%"], ["错误导向 SFT", "35.5%", "31.5%", "99% / 100%"]],
    observations: ["错误导向 SFT 在 Prompt A 下仅高于随机 SFT 1 个百分点，McNemar 检验 p=0.8679，没有证据支持稳定差异。", "基础模型的 106 个失败中，关系建模错误占 57.5%，算术错误占 10.4%。", "结构化 Prompt C 在三种模型设置下名义正确率均下降，但 A/C 的配对差异未达到统计显著。"],
    limitations: "结论限于固定模型、提示、1,000 样本 LoRA 设置与 200 题 holdout。错误分类经过模型辅助标注及一致性抽查，不等于完整人工标注。冻结测试集不能再用于调参后报告最终性能。",
    contribution: "个人完成推理后端、答案解析、数据选样与训练流程、统一评测、配对统计和错误分析，保存实验配置、数据清单与冻结结果。",
    next: "把关系建模作为进一步诊断方向；若继续训练或选择策略，使用新的 holdout 验证，并分别报告格式与数学正确性。",
  },
];
